# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/typescript-node
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:18

# Install Gemini CLI
RUN npm install -g @google/gemini-cli

